services:
  iris:
    image: ghcr.io/l8tenever/iris:latest
    container_name: iris
    ports:
      - "5000:5000"
    volumes:
      - iris_db:/app/iris.db
      - iris_uploads:/app/static/uploads
    restart: unless-stopped

volumes:
  iris_db:
  iris_uploads:
